//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DGII_RNC
    {
        public string RNC { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string ActividadEconomica { get; set; }
        public string FechaAfiliacion { get; set; }
        public string Estado { get; set; }
        public string TipoEmp { get; set; }
    }
}
