//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SadoraEntity : DbContext
    {
        public SadoraEntity()
            : base("name=SadoraEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TsysAcceso> TsysAccesos { get; set; }
        public virtual DbSet<TsysFormulario> TsysFormularios { get; set; }
        public virtual DbSet<TsysUsuario> TsysUsuarios { get; set; }
        public virtual DbSet<TconComprobante> TconComprobantes { get; set; }
        public virtual DbSet<TsysEmpresa> TsysEmpresas { get; set; }
        public virtual DbSet<TsupProveedore> TsupProveedores { get; set; }
        public virtual DbSet<CeduladosJCE> CeduladosJCEs { get; set; }
        public virtual DbSet<DGII_RNC> DGII_RNC { get; set; }
        public virtual DbSet<TcliCliente> TcliClientes { get; set; }
    }
}
