//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TcliMovimientosCuenta
    {
        public int RowID { get; set; }
        public Nullable<int> MovimientoID { get; set; }
        public string TipoMovimiento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Debito { get; set; }
        public Nullable<double> Credito { get; set; }
    }
}
