//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using Sadora.ViewModels;
    using System;

    public partial class TcliCliente : BaseViewModel
    {
        public int ClienteID 
        { 
            get => Get<int>(); 
            set => Set(value); 
        }
        public string RNC
        {
            get => Get<string>();
            set => Set(value);
        }
        public string Nombre
        {
            get => Get<string>();
            set => Set(value);
        }
        public string Representante
        {
            get => Get<string>();
            set => Set(value);
        }
        public Nullable<int> ClaseID
        {
            get => Get<int>();
            set => Set(value);
        }
        public string Direccion
        {
            get => Get<string>();
            set => Set(value);
        }
        public string CorreoElectronico
        {
            get => Get<string>();
            set => Set(value);
        }
        public string Telefono
        {
            get => Get<string>();
            set => Set(value);
        }
        public string Celular
        {
            get => Get<string>();
            set => Set(value);
        }
        public Nullable<bool> Activo
        {
            get => Get<bool>();
            set => Set(value);
        }
        public Nullable<int> UsuarioID
        {
            get => Get<int>();
            set => Set(value);
        }
        public int ClaseComprobanteID
        {
            get => Get<int>();
            set => Set(value);
        }
        public Nullable<int> DiasCredito
        {
            get => Get<int>();
            set => Set(value);
        }
    }
}
