//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TconComprobante
    {
        public int RowID { get; set; }
        public int ComprobanteID { get; set; }
        public string Nombre { get; set; }
        public string Auxiliar { get; set; }
        public string Nomenclatura { get; set; }
        public Nullable<int> Desde { get; set; }
        public Nullable<int> Hasta { get; set; }
        public string NextNCF { get; set; }
        public Nullable<int> Disponibles { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<bool> SinComprobantes { get; set; }
    }
}
