//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinvServicioArticulo
    {
        public int RowID { get; set; }
        public Nullable<int> ArticuloID { get; set; }
        public string NombreServicio { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<bool> Alta { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    }
}
