//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinvMovimientoInventarioDetalle
    {
        public int RowID { get; set; }
        public Nullable<int> MovimientoID { get; set; }
        public string ArticuloID { get; set; }
        public string TarjetaID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> CantidadPrevia { get; set; }
        public Nullable<int> CantidadPostMovimiento { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    }
}
