//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinvArticulo
    {
        public int RowID { get; set; }
        public int ArticuloID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> ClaseArticuloID { get; set; }
        public Nullable<int> DepartamentoID { get; set; }
        public int MarcaID { get; set; }
        public string Tarjeta { get; set; }
        public double Costo { get; set; }
        public double Precio { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<bool> HaveServices { get; set; }
    }
}
