//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinvServicioArticulo
    {
        public int RowID { get; set; }
        public Nullable<int> ArticuloID { get; set; }
        public string NombreServicio { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<bool> Alta { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    }
}
