//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinvArticulo
    {
        public int RowID { get; set; }
        public int ArticuloID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> ClaseArticuloID { get; set; }
        public Nullable<int> DepartamentoID { get; set; }
        public int MarcaID { get; set; }
        public string Tarjeta { get; set; }
        public double Costo { get; set; }
        public double Precio { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<bool> HaveServices { get; set; }
    }
}
