//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinvMovimientoInventario
    {
        public int RowID { get; set; }
        public Nullable<int> MovimientoID { get; set; }
        public string TipoMovimiento { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public string Estado { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    }
}
