//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinvMovimientoInventarioDetalle
    {
        public int RowID { get; set; }
        public Nullable<int> MovimientoID { get; set; }
        public string ArticuloID { get; set; }
        public string TarjetaID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> CantidadPrevia { get; set; }
        public Nullable<int> CantidadPostMovimiento { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    }
}
