//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsupTransaccione
    {
        public int RowID { get; set; }
        public Nullable<int> TransaccionID { get; set; }
        public string TipoTransaccion { get; set; }
        public Nullable<int> ProveedorID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> MontoExcento { get; set; }
        public Nullable<double> MontoGravado { get; set; }
        public Nullable<double> ITBIS { get; set; }
        public string Estado { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    }
}
