//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsupProveedore
    {
        public int RowID { get; set; }
        public Nullable<int> ProveedorID { get; set; }
        public string RNC { get; set; }
        public string Nombre { get; set; }
        public string Representante { get; set; }
        public Nullable<int> ClaseID { get; set; }
        public string Direccion { get; set; }
        public string CorreoElectronico { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    }
}
