//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsysAcceso
    {
        public int RowID { get; set; }
        public int UsuarioID { get; set; }
        public string Nombre { get; set; }
        public string Modulo { get; set; }
        public string Titulo { get; set; }
        public Nullable<bool> Visualiza { get; set; }
        public Nullable<bool> Imprime { get; set; }
        public Nullable<bool> Agrega { get; set; }
        public Nullable<bool> Modifica { get; set; }
        public Nullable<bool> Anula { get; set; }
    }
}
