//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsysEmpresa
    {
        public int RowID { get; set; }
        public Nullable<int> EmpresaID { get; set; }
        public string Nombre { get; set; }
        public string RNC { get; set; }
        public string Razon_Social { get; set; }
        public string Direccion { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string Telefono { get; set; }
    }
}
