//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsysGruposAcceso
    {
        public int RowID { get; set; }
        public Nullable<int> GrupoID { get; set; }
        public string Nombre { get; set; }
        public string Modulo { get; set; }
        public string Titulo { get; set; }
        public Nullable<bool> Visualiza { get; set; }
        public Nullable<bool> Imprime { get; set; }
        public Nullable<bool> Agrega { get; set; }
        public Nullable<bool> Modifica { get; set; }
        public Nullable<bool> Anula { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    }
}
