//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsysEmpresa
    {
        public int RowID { get; set; }
        public Nullable<int> EmpresaID { get; set; }
        public string Nombre { get; set; }
        public string RNC { get; set; }
        public string Razon_Social { get; set; }
        public string Direccion { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string Telefono { get; set; }
    }
}
