//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TvenFacturasDetalle
    {
        public int RowID { get; set; }
        public int FacturaID { get; set; }
        public int ArticuloID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public double Precio { get; set; }
        public double Descuento { get; set; }
        public double SubTotal { get; set; }
        public double ITBIS { get; set; }
        public double Total { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string NombreArticulo { get; set; }
    }
}
